name: Pruebas Unitarias - Funcionales

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout del Código
      uses: actions/checkout@v2
      with:
        repository: DaromanX/gestion-de-proyectos
        path: Code/Web/Scripts

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cambiar al Directorio del Proyecto
      run: cd Code\Web\GestionDeProyectos

    - name: Ejecucion de Pruebas Unitarias
      run: python manage.py test apps.core.tests.tests_unitario

    - name: Ejecucion de Pruebas Funcionales
      run: python manage.py test apps.core.tests.tests_functional
