name: Pruebas Selenium - Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout del Código
      uses: actions/checkout@v2
      with:
        repository: daromanx/gestion-de-proyectos

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cambiar al Directorio del Proyecto
      run: cd Code\Web\GestionDeProyectos  # Ajusta la ruta según tu estructura

    - name: Ejecutar Pruebas Selenium
      run: |
        python manage.py test apps.core.tests.selenium_tests  # Ajusta según tus pruebas de Selenium
