name: Pruebas Unitarias - Funcionales

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout del Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        cd Code\Web\Scripts
        pip install -r requirements.txt

    - name: Ejecucion de Pruebas Unitarias
      run: |
        cd Code\Web\GestionDeProyectos
        python manage.py test apps.core.tests.tests_unitario

    - name: Ejecucion de Pruebas Funcionales
      run: |
        cd Code\Web\GestionDeProyectos
        python manage.py test apps.core.tests.tests_functional


    
