name: Pruebas Unitarias y Funcionales con Cobertura

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout del Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        cd Code\Web\Scripts
        pip install -r requirements.txt

    - name: Ejecutar Pruebas Unitarias con Cobertura
      run: |
        cd Code\Web\GestionDeProyectos
        coverage run --source='.' manage.py test apps.core.tests.tests_unitario
        coverage report
        coverage html

    - name: Ejecutar Pruebas Funcionales con Cobertura
      run: |
        cd Code\Web\GestionDeProyectos
        coverage run --source='.' manage.py test apps.core.tests.tests_functional
        coverage report
        coverage html

    - name: Subir Reporte de Cobertura a Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
